# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Deploy

on:
  push:
    branches: [ "main", "develop/*"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:            # 수동으로 CI/CD 수행

# 변수 설정
env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: naejango-github-actions-s3-bucket
  CODE_DEPLOY_APPLICATION_NAME: my-codedeloy-app
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: my-codedeploy-group
  SECURITY_GROUP_NAME: rds-security
  EC2_SECURITY_GROUP_NAME: ec2-security
  BRANCH_NAME: $(echo $GITHUB_REF | awk -F'/' '{print $3}')
  DEPLOY_STRATEGY: blue-green

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # (1) Checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          submodules: true

      # (2) JDK 11 셋팅
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # (3) DB 셋팅
      - name: Set up Postgresql DB
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '14'

      # (4) 빌드 (RDS 접근 권한 설정)
        # (4-1) AWS 권한 획득 (RDS 서버)
      - name: Configure AWS RDS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.RDS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.RDS_SECRET_KEY }}
          aws-region: ap-northeast-2

        # (4-2) 깃허브 액션 러너의 아이피 얻어오기
      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.2

        # (4-3) RDS 보안 그룹에 깃허브 러너 IP 인바운드 규칙 추가
      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-name ${{ env.SECURITY_GROUP_NAME }} --protocol tcp --port 5432 --cidr ${{ steps.ip.outputs.ipv4 }}/32 

        # (4-4) 빌드 권한 획득
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

        # (4-5) 빌드
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build

        # (4-6) RDS 보안 그룹에서 깃허브 러너 IP 삭제
      - name: Remove Github Actions IP from security group
        run: |
          aws ec2 revoke-security-group-ingress --group-name ${{ env.SECURITY_GROUP_NAME }} --protocol tcp --port 5432 --cidr ${{ steps.ip.outputs.ipv4 }}/32 

      # (5) 무중단 배포
       # (5-1) docker 이미지 build 및 push
      - name: Docker build & push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/naejango-server:${{ env.BRANCH_NAME }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/naejango-server:${{ env.BRANCH_NAME }}

      # (5-2) AWS 권한 획득 (EC2 서버)
      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.EC2_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.EC2_USER_SECRET_KEY }}
          aws-region: ap-northeast-2

      # (5-3) EC2 보안 그룹에 깃허브 러너 IP 인바운드 규칙 추가
      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-name ${{ env.EC2_SECURITY_GROUP_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32 

      # (5-4) EC2 에 ssh 로 접속하여 배포 스크립트를 실행
      - name: Deploy to EC2 (develop)
        uses: appleboy/ssh-action@master
        if: ${{ env.BRANCH_NAME }} == 'develop'
        with:
          host: ${{ secrets.HOST_DNS }} # EC2 퍼블릭 IPv4 DNS
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo sh /home/ec2-user/cicd/deploy.sh ${{ env.BRANCH_NAME }} develop

      # (5-4) EC2 에 ssh 로 접속하여 배포 스크립트를 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        if: ${{ env.BRANCH_NAME }} == 'main'
        with:
          host: ${{ secrets.HOST_DNS }} # EC2 퍼블릭 IPv4 DNS
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo sh /home/ec2-user/cicd/deploy.sh ${{ github.base_ref }} ${{ env.DEPLOY_STRATEGY }}
            

      # (5-5) EC2 보안 그룹에서 깃허브 러너 IP 규칙 삭제
      - name: Remove Github Actions IP from security group
        run: |
          aws ec2 revoke-security-group-ingress --group-name ${{ env.EC2_SECURITY_GROUP_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32